# Generated by Django 4.0.4 on 2022-04-16 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0002_competence_providercompetence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProviderCompetence',
            new_name='CompanyCompetence',
        ),
        migrations.RenameModel(
            old_name='Provider',
            new_name='Company',
        ),
        migrations.CreateModel(
            name='QuotationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('documentation', models.FileField(upload_to='uploads/docs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence.company')),
            ],
        ),
    ]
